### ISSUE TITLE
[CoreOS-semanage]: not working `ignored due to incompatible image`

### ISSUE THREAD

**Issue by vic1707** [travier/fedora-sysexts#125]
I don't know if I'm missing something or if the release has an issue.

butane:
```yml
# {{ $ARCH:= "aarch64" }} # TODO: from env
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/Relativ-IT/Butane-Schemas/Release/Butane-Schema.json
variant: fcos
version: 1.6.0

storage:
  files:
    - path: /var/lib/extensions/semanage.raw
      contents:
        source: https://github.com/travier/fedora-sysexts/releases/download/semanage-3.8-1.fc42-42-{{$ARCH}}/semanage-3.8-1.fc42-42-{{$ARCH}}.raw
```

```sh
[vic1707@localhost ~]$ systemd-sysext status
HIERARCHY EXTENSIONS SINCE
/opt      none       -    
/usr      none       -    
[vic1707@localhost ~]$ sudo systemd-sysext refresh
No suitable extensions found (1 ignored due to incompatible image(s)).
[vic1707@localhost ~]$ systemd-sysext list
NAME     TYPE PATH                             TIME                        
semanage raw  /var/lib/extensions/semanage.raw Sun 2025-06-08 19:21:07 CEST
[vic1707@localhost ~]$ sha256sum /var/lib/extensions/semanage.raw
c738b80a824597d930a8ec1a737678a4fe3b8d540fae07c457d68925720159bc  /var/lib/extensions/semanage.raw
[vic1707@localhost ~]$ uname -a
Linux localhost.localdomain 6.14.5-300.fc42.aarch64 #1 SMP PREEMPT_DYNAMIC Fri May  2 14:31:46 UTC 2025 aarch64 GNU/Linux
[vic1707@localhost ~]$ 
```
The sha is correct, I believe the path is right so I'm kinda clueless as to why it throws that error 😓
